import { motion } from 'motion/react';
import { ArrowLeft } from 'lucide-react';
import { Button } from '@/app/components/ui/button';
import { PhoenixLogo } from './PhoenixLogo';

interface PrivacyPolicyProps {
  onBack: () => void;
}

export function PrivacyPolicy({ onBack }: PrivacyPolicyProps) {
  return (
    <div className="min-h-screen bg-[#0D0D0D] text-white">
      {/* Header */}
      <header className="sticky top-0 z-50 backdrop-blur-xl bg-[#0D0D0D]/80 border-b border-[#374151]">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <PhoenixLogo size="sm" animated={false} />
              <span className="text-xl bg-gradient-to-r from-[#FF6B35] to-[#F59E0B] bg-clip-text text-transparent">
                Project Phoenix
              </span>
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={onBack}
              className="border-[#FF6B35] text-[#FF6B35] hover:bg-[#FF6B35]/10"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back
            </Button>
          </div>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <h1 className="text-4xl sm:text-5xl mb-4">
            <span className="bg-gradient-to-r from-[#FF6B35] to-[#F59E0B] bg-clip-text text-transparent">
              Privacy Policy
            </span>
          </h1>
          <p className="text-xl text-[#9CA3AF] mb-2">
            Project Phoenix - Vitruvian Trainer Companion App
          </p>
          <p className="text-sm text-[#6B7280] mb-8">
            Effective Date: December 21, 2025
          </p>

          {/* Summary Box */}
          <div className="mb-12 p-6 rounded-lg bg-gradient-to-br from-[#FF6B35]/10 to-[#DC2626]/10 border-2 border-[#FF6B35]/30">
            <p className="text-lg text-[#E5E7EB]">
              <span className="font-semibold text-[#FF6B35]">Summary:</span> Project Phoenix is a privacy-focused, offline-first app. Your workout data stays on your device. We do not collect, transmit, or sell your personal information.
            </p>
          </div>

          {/* Policy Sections */}
          <div className="space-y-8">
            <section>
              <h2 className="text-2xl mb-4 text-[#FF6B35]">1. Introduction</h2>
              <p className="text-[#E5E7EB] leading-relaxed">
                Project Phoenix ("we," "our," or "the App") is a community-developed companion application for Vitruvian Trainer fitness equipment. We are committed to protecting your privacy and being transparent about our data practices.
              </p>
              <p className="text-[#E5E7EB] leading-relaxed mt-4">
                This Privacy Policy explains what information the App accesses, how it is used, and your rights regarding your data.
              </p>
            </section>

            <section>
              <h2 className="text-2xl mb-4 text-[#FF6B35]">2. Information We Collect</h2>
              <p className="text-[#E5E7EB] leading-relaxed mb-4">
                <span className="font-semibold">We do not collect any personal information.</span> All data generated by the App is stored locally on your device and is never transmitted to external servers.
              </p>
              <p className="text-[#E5E7EB] leading-relaxed mb-3">
                The App stores the following data locally on your device:
              </p>
              <ul className="space-y-2 text-[#E5E7EB] ml-6">
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span><span className="font-semibold">Workout Data:</span> Exercise sessions, sets, reps, weights, and timestamps</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span><span className="font-semibold">Performance Metrics:</span> Real-time machine data during workouts (position, velocity, load, power)</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span><span className="font-semibold">Personal Records:</span> Your best lifts and calculated one-rep max estimates</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span><span className="font-semibold">Custom Routines:</span> Workout routines you create within the App</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span><span className="font-semibold">App Preferences:</span> Your settings such as weight unit preference (kg/lb), theme, and display options</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span><span className="font-semibold">Gamification Data:</span> Badges earned and achievement progress</span>
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl mb-4 text-[#FF6B35]">3. Bluetooth Permissions</h2>
              <p className="text-[#E5E7EB] leading-relaxed mb-3">
                The App requires Bluetooth Low Energy (BLE) permissions to connect to your Vitruvian Trainer equipment. This connection is used exclusively for:
              </p>
              <ul className="space-y-2 text-[#E5E7EB] ml-6 mb-4">
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span>Discovering and connecting to your Vitruvian machine</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span>Sending workout commands (weight, mode settings)</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span>Receiving real-time workout metrics from the machine</span>
                </li>
              </ul>
              <p className="text-[#E5E7EB] leading-relaxed">
                Bluetooth data is processed in real-time and relevant metrics are stored locally. No Bluetooth data is transmitted to external parties.
              </p>
            </section>

            <section>
              <h2 className="text-2xl mb-4 text-[#FF6B35]">4. Data Storage and Security</h2>
              <p className="text-[#E5E7EB] leading-relaxed mb-4">
                All your data is stored locally on your device using secure, encrypted storage mechanisms provided by the operating system. Your data remains under your control at all times.
              </p>
              <ul className="space-y-2 text-[#E5E7EB] ml-6">
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span><span className="font-semibold">No Cloud Sync:</span> Your data is not uploaded to any cloud service</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span><span className="font-semibold">No Account Required:</span> You do not need to create an account to use the App</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span><span className="font-semibold">No External Servers:</span> The App does not communicate with any external servers</span>
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl mb-4 text-[#FF6B35]">5. Third-Party Services</h2>
              <p className="text-[#E5E7EB] leading-relaxed mb-3">
                The App does not integrate with any third-party analytics, advertising, or tracking services. We do not use:
              </p>
              <ul className="space-y-2 text-[#E5E7EB] ml-6">
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span>Google Analytics or Firebase Analytics</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span>Crash reporting services (Crashlytics, Sentry, etc.)</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span>Advertising networks</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span>Social media SDKs</span>
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl mb-4 text-[#FF6B35]">6. Data Sharing</h2>
              <p className="text-[#E5E7EB] leading-relaxed">
                <span className="font-semibold">We do not share your data with anyone.</span> Since all data is stored locally on your device and never transmitted externally, there is no data to share with third parties.
              </p>
            </section>

            <section>
              <h2 className="text-2xl mb-4 text-[#FF6B35]">7. Your Rights and Data Control</h2>
              <p className="text-[#E5E7EB] leading-relaxed mb-3">
                You have complete control over your data:
              </p>
              <ul className="space-y-2 text-[#E5E7EB] ml-6 mb-4">
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span><span className="font-semibold">Access:</span> All your data is visible within the App's history and analytics screens</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span><span className="font-semibold">Deletion:</span> You can delete individual workouts, routines, or clear all App data through your device settings</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span><span className="font-semibold">Portability:</span> Your data remains on your device and can be backed up using your device's standard backup mechanisms</span>
                </li>
              </ul>
              <p className="text-[#E5E7EB] leading-relaxed">
                To delete all App data, you can uninstall the App or clear the App's data through your device's application settings.
              </p>
            </section>

            <section>
              <h2 className="text-2xl mb-4 text-[#FF6B35]">8. Children's Privacy</h2>
              <p className="text-[#E5E7EB] leading-relaxed">
                The App is not directed at children under the age of 13. We do not knowingly collect any information from children. The App is designed for adult fitness enthusiasts using Vitruvian Trainer equipment.
              </p>
            </section>

            <section>
              <h2 className="text-2xl mb-4 text-[#FF6B35]">9. Changes to This Privacy Policy</h2>
              <p className="text-[#E5E7EB] leading-relaxed">
                We may update this Privacy Policy from time to time. Any changes will be reflected on this page with an updated effective date. We encourage you to review this Privacy Policy periodically.
              </p>
            </section>

            <section>
              <h2 className="text-2xl mb-4 text-[#FF6B35]">10. Open Source</h2>
              <p className="text-[#E5E7EB] leading-relaxed">
                Project Phoenix is an open-source, community-driven project. You can review our source code to verify our privacy practices at any time.
              </p>
            </section>

            <section>
              <h2 className="text-2xl mb-4 text-[#FF6B35]">11. Contact Us</h2>
              <p className="text-[#E5E7EB] leading-relaxed mb-3">
                If you have any questions about this Privacy Policy or the App's data practices, you can:
              </p>
              <ul className="space-y-2 text-[#E5E7EB] ml-6">
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span>Open an issue on our GitHub repository</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#FF6B35] mt-1">•</span>
                  <span>Support the project: <a href="https://ko-fi.com/vitruvianredux" target="_blank" rel="noopener noreferrer" className="text-[#FF6B35] hover:text-[#F59E0B] underline">ko-fi.com/vitruvianredux</a></span>
                </li>
              </ul>
            </section>
          </div>

          {/* Back Button */}
          <div className="mt-12 text-center">
            <Button
              onClick={onBack}
              className="bg-gradient-to-r from-[#FF6B35] to-[#DC2626] hover:from-[#DC2626] hover:to-[#F59E0B] border-0"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Home
            </Button>
          </div>
        </motion.div>
      </main>

      {/* Footer */}
      <footer className="border-t border-[#374151] py-8 mt-12">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <p className="text-[#6B7280] text-sm">
            © 2026 9th Level Software LLC. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
